version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -m venv ./virtualenvs/tap-s3-csv
            . ./virtualenvs/tap-s3-csv/bin/activate
            pip3 install --upgrade pip
            pip3 install .[test]
      - run:
          name: 'Pylinting'
          command: |
            . ./virtualenvs/tap-s3-csv/bin/activate
            pylint --rcfile .pylintrc tap_s3_csv/
      - run:
          name: 'Unit Tests'
          command: |
            . ./virtualenvs/tap-s3-csv/bin/activate
            export LOGGING_CONF_FILE=./sample_logging.conf
            nosetests tests

workflows:
  version: 2
  build:
    jobs:
      - build
